### ISSUE TITLE
Replace HTTP Auth with real user model and sessions

### ISSUE THREAD

**Issue by nmertaugh** [Pantelope/mothership#1]
@kirkland - we should consider using real sessions so we can conditionally reveal CRUD buttons to admins on the blog. Let's brainstorm some light weight gems to use, like:

* [`sorcery`](https://github.com/NoamB/sorcery)
* [`clearance`](https://github.com/thoughtbot/clearance)

I like `clearance`, as it's pretty gosh darned slender.

What do you think?

**Comment by nmertaugh** [comment]
@kirkland - part of this ticket should be to modify the `Post` model so it is associated with a `User`. Right now it just has an `author` attribute which holds a string.

**Comment by kirkland** [comment]
Clearance looks fine to me. I can take this ticket unless you really want it.

**Comment by nmertaugh** [comment]
Have at it @kirkland! I've got a ticket for markdown parsing, so I've got some work to bang on.

**Comment by nmertaugh** [comment]
Oh - same old routine good for you? feature branches -> code review -> merge -> deploy?

**Comment by jjannetty** [comment]
Who is going to review my branches...

**Comment by nmertaugh** [comment]
The other you? JK - we can still review for style and whatnot, maybe every now and then we'll need view specs or something... Don't be shy!

**Comment by kirkland** [comment]
@nmertaugh yes, totally down with that work flow.

**Comment by kirkland** [comment]
Done with 08447ed745750a0cbd1d926fbe6967d8501db538
